theme: jekyll-theme-hacker
title: Blog
author: mulpdev

# social links
github_username:  mulpdev # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
